server:
  port: 8091
  servlet:
    context-path: /debezium

management:
  endpoints:
    web:
      exposure:
        include: "*"


#spring:
#  datasource:
#    url: jdbc:oracle:thin:@172.16.17.104:1521:xe
#    hikari:
#      username: CDC
#      password: 123456
#      driver-class-name: oracle.jdbc.driver.OracleDriver
spring:
  datasource:
    url: jdbc:mysql://172.16.17.105:3306/cdc?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      username: root
      password: 123456
      #      mysql版本 >= 6.x com.mysql.cj.jdbc.Driver
      #      mysql版本 <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: debezium-kafka-connector
      key-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      #      配置schema存放的仓库
      properties:
        schema.registry.url: http://localhost:8081


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: Auto
      table-underline: true # 默认数据库字段为下划线格式
      logic-delete-field: del_flag  # 逻辑删除字段
      logic-delete-value: 1 # 删除
      logic-not-delete-value: 0 # 正常
  configuration:
    call-setters-on-nulls: true
  type-enums-package: com.zsrd.enums # 枚举类型

logging:
  config: classpath:logback-spring.xml
  level:
    com.zsrd.debezium.mapper: debug

